esphome:
  name: esp32c3-supermini
  friendly_name: ESP32-C3 Super Mini

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  power_save_mode: none
  output_power: 8.5dB  # Snížený výkon pro stabilitu C3
  reboot_timeout: 60s  # Po 60s bez Wi-Fi se ESP restartuje a spustí AP
  
  # Fallback AP hotspot
  ap:
    ssid: "ESP32-C3-Fallback"
    password: !secret ap_password

# Captive portal pro snadné připojení k fallback AP
captive_portal:
